# Generated by Django 6.0.4 on 2026-04-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descripcion',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
