# Generated by Django 6.0.4 on 2026-04-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estado',
            field=models.CharField(choices=[('Sin_previo', 'Sin previo'), ('Grabando', 'Para Grabar'), ('Entregar', 'Para Entregar')], default='Sin previo', max_length=20),
        ),
    ]
